### ISSUE TITLE
AttributeError: 'YTick' object has no attribute 'label'

### ISSUE THREAD

**Issue by zvirblyte** [DendrouLab/panpipes#104]
While running 'panpipes ingest make full --local' locally on my computer I receive this error: AttributeError: 'YTick' object has no attribute 'label'.

I guess it has to do something with matplotlib.

 Full error code:

    Traceback (most recent call last):
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
        return_value = job_wrapper(params, user_defined_work_func,
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/ruffus/task.py", line 608, in job_wrapper_output_files
        job_wrapper_io_files(params, user_defined_work_func, register_cleanup, touch_files_only,
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/ruffus/task.py", line 540, in job_wrapper_io_files
        ret_val = user_defined_work_func(*(params[1:]))
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/panpipes/panpipes/pipeline_ingest.py", line 469, in run_dsb_clr
        P.run(cmd, **job_kwargs)
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/cgatcore/pipeline/execution.py", line 1244, in run
        benchmark_data = r.run(statement_list)
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/cgatcore/pipeline/execution.py", line 1029, in run
        raise OSError(
    OSError: ---------------------------------------
    Child was terminated by signal -1:
    The stderr was:
    /Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
      self.seed = seed
    /Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
      self.dl_pin_memory_gpu_training = (
    /Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/muon/_prot/preproc.py:219: UserWarning: adata.X is sparse but not in CSC format. Converting to CSC.
      warn("adata.X is sparse but not in CSC format. Converting to CSC.")
    Traceback (most recent call last):
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/panpipes/python_scripts/run_preprocess_prot.py", line 144, in <module>
        pnp.plotting.ridgeplot(mdata["prot"], features=plot_features, layer="clr",  splitplot=6)
      File "/Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/panpipes/funcs/plotting.py", line 299, in ridgeplot
        tick.label.set_fontsize(10)
    AttributeError: 'YTick' object has no attribute 'label'

    python /Users/justina/opt/anaconda3/envs/multiome_panpipes/lib/python3.9/site-packages/panpipes/python_scripts/run_preprocess_prot.py         --filtered_mudata test_unfilt.h5mu         --figpath ./figures/prot          --channel_col sample_id --normalisation_methods clr --quantile_clipping True --clr_margin 0 > logs/run_dsb_clr.log

Matplotlib version: 3.8.0

**Comment by bio-la** [comment]
thanks @zvirblyte for using panpipes!
i can confirm i can replicate this issue with `matplotlib==3.8.0`
working on this, stay tuned!

**Comment by bio-la** [comment]
this issue is fixed in #106. 
as a temporary fix you can downgrade the version of matplotlib to 3.7.*

we will fix the versioning of matplotlib in a stable panpipes release and work on supporting the new matplotlib 3.8 in a future release.

i leave this issue open for now to remember to document it.
thanks @zvirblyte for your feedback!

f

**Comment by bio-la** [comment]
fixed in release https://github.com/DendrouLab/panpipes/tree/v0.3.1

**Comment by JHYSiu** [comment]
Hi. Was wondering if this was going to be fixed properly so that latest matplotlib can be used? Thanks! 

<img width="2936" height="408" alt="Image" src="https://github.com/user-attachments/assets/bbb18d53-19eb-4b9c-b947-36905ed864a0" />
